server:
  port: ${SERVER-PORT:8083}
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: demo-admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA-SERVER:localhost}:${EUREKA-PORT:8084}/eureka/
  instance:
    prefer-ip-address: true
